Repository LeonasAnony/Kontaktformular, pull requests merged in 2021-03, with the labels that each got.

#9 Dev
  README.md
  formular.php
  logout.php
  src/crypto_helper.php
  src/helper.php
Labels: enhancement

#12 Fixing Issue #10 and #11
  formular.php
  logout.php
Labels: enhancement

#13 Reorganizing p's
  formular.php
  logout.php
  resource/style.css
Labels: enhancement, fixed/ added

#14 Added translation logic
  formular.php
  logout.php
  resource/style.css
  src/locale/de.php
  src/locale/en.php
  src/locale/es.php
  src/locale/fr.php
Labels: enhancement

#18 Adding export page
  export.php
  src/crypto_helper.php
  src/csv_helper.php
Labels: enhancement, fixed/ added

#19 Fixed Issue #17
  formular.php
  src/locale/de.php
  src/locale/en.php
  src/locale/es.php
  src/locale/fr.php
Labels: bug, fixed/ added

#22 fix alot of differnet things and add some sec to gen keys
  README.md
  csv_export.php
  formular.php
  src/crypto_conf.php
  src/crypto_helper.php
  src/gen_keys.php
Labels: enhancement
